import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { logger } from "@/lib/logger";
import { rateLimit, rateLimitResponse } from "@/lib/rate-limit";

function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim());
}

export async function POST(req: NextRequest) {
  // Rate limit: 20 invitations per 10 minutes per IP
  const rl = await rateLimit(req, { limit: 20, window: 600 });
  if (!rl.success) return rateLimitResponse(rl.resetAt);

  try {
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Nicht autorisiert" }, { status: 401 });
    }

    const body = await req.json() as { email?: string; name?: string };
    const { email, name } = body;

    if (!email || !isValidEmail(email)) {
      return NextResponse.json({ error: "Ungültige E-Mail-Adresse" }, { status: 400 });
    }

    // Check that the calling user is admin of a Unternehmen
    const { data: unternehmen, error: unternehmenErr } = await supabase
      .from("unternehmen")
      .select("id, name, max_mitarbeiter, aktive_mitarbeiter, subscription_status")
      .eq("admin_user_id", user.id)
      .single();

    if (unternehmenErr || !unternehmen) {
      return NextResponse.json(
        { error: "Kein Unternehmen gefunden. Bitte zuerst registrieren." },
        { status: 403 }
      );
    }

    // Check subscription is not cancelled
    if (unternehmen.subscription_status === "gekuendigt") {
      return NextResponse.json(
        { error: "Ihr Abonnement wurde beendet. Bitte kontaktieren Sie den Support." },
        { status: 403 }
      );
    }

    // Check capacity
    if (unternehmen.aktive_mitarbeiter >= unternehmen.max_mitarbeiter) {
      return NextResponse.json(
        {
          error: `Lizenzlimit erreicht (${unternehmen.max_mitarbeiter} Mitarbeiter). Bitte upgraden Sie Ihren Plan.`,
        },
        { status: 403 }
      );
    }

    const normalizedEmail = email.trim().toLowerCase();

    // Check not already a member
    const { data: existingMember } = await supabase
      .from("unternehmen_mitarbeiter")
      .select("id")
      .eq("unternehmen_id", unternehmen.id)
      .eq("status", "aktiv")
      .limit(1);

    // We can't easily join on email here without joining auth.users
    // Instead check pending invitations for this email
    const { data: existingInvite } = await supabase
      .from("mitarbeiter_einladungen")
      .select("id, status")
      .eq("unternehmen_id", unternehmen.id)
      .eq("email", normalizedEmail)
      .eq("status", "ausstehend")
      .single();

    if (existingInvite) {
      return NextResponse.json(
        { error: "Für diese E-Mail-Adresse liegt bereits eine ausstehende Einladung vor." },
        { status: 409 }
      );
    }

    // Create the invitation record (token is auto-generated by DB default)
    const { data: einladung, error: insertErr } = await supabase
      .from("mitarbeiter_einladungen")
      .insert({
        unternehmen_id: unternehmen.id,
        eingeladen_von: user.id,
        email: normalizedEmail,
        name: name?.trim() || null,
      })
      .select("id, token")
      .single();

    if (insertErr || !einladung) {
      logger.error("B2B: Einladung erstellen fehlgeschlagen", { error: insertErr });
      return NextResponse.json({ error: "Fehler beim Erstellen der Einladung" }, { status: 500 });
    }

    const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://xcare.app";
    const einladungsLink = `${appUrl}/einladung/${einladung.token}`;

    // Send invitation email via Resend
    const resendApiKey = process.env.RESEND_API_KEY;
    if (resendApiKey) {
      try {
        const emailRes = await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${resendApiKey}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            from: "xcare for Business <noreply@xcare.app>",
            to: normalizedEmail,
            subject: `${unternehmen.name} hat Sie zu xcare eingeladen`,
            html: `
<!DOCTYPE html>
<html lang="de">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f9fafb; margin: 0; padding: 32px 16px;">
  <div style="max-width: 500px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; border: 1px solid #e5e7eb;">
    <div style="background: #1d4ed8; padding: 24px 32px;">
      <h1 style="color: white; font-size: 22px; margin: 0; font-weight: 700;">xcare for Business</h1>
    </div>
    <div style="padding: 32px;">
      <h2 style="font-size: 18px; font-weight: 600; color: #111827; margin-top: 0;">
        Sie wurden eingeladen!
      </h2>
      <p style="color: #374151; line-height: 1.6; margin-bottom: 8px;">
        Hallo${name ? ` ${name.trim()}` : ""},
      </p>
      <p style="color: #374151; line-height: 1.6;">
        <strong>${unternehmen.name}</strong> hat Sie eingeladen, xcare als Mitarbeiter-Benefit zu nutzen.
        Mit xcare erhalten Sie Zugang zu professioneller Pflegeberatung, Anbietersuche und weiteren Funktionen.
      </p>
      <div style="margin: 28px 0;">
        <a href="${einladungsLink}"
           style="display: inline-block; background: #1d4ed8; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 15px;">
          Einladung annehmen
        </a>
      </div>
      <p style="color: #6b7280; font-size: 13px; line-height: 1.5;">
        Oder kopieren Sie diesen Link in Ihren Browser:<br>
        <span style="word-break: break-all; color: #2563eb;">${einladungsLink}</span>
      </p>
      <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;">
      <p style="color: #9ca3af; font-size: 12px; margin: 0;">
        Diese Einladung ist 7 Tage gültig. Falls Sie diese E-Mail nicht erwartet haben, können Sie sie ignorieren.
      </p>
    </div>
  </div>
</body>
</html>`,
          }),
        });

        if (!emailRes.ok) {
          logger.warn("B2B: E-Mail-Versand fehlgeschlagen", {
            status: emailRes.status,
            einladungId: einladung.id,
          });
        }
      } catch (emailErr) {
        logger.warn("B2B: Resend-Fehler", { error: String(emailErr) });
        // Continue — invitation was created, email sending is best-effort
      }
    } else {
      logger.warn("B2B: RESEND_API_KEY nicht konfiguriert, E-Mail nicht versendet");
    }

    return NextResponse.json({
      success: true,
      einladungId: einladung.id,
      message: `Einladung an ${normalizedEmail} wurde verschickt.`,
    });
  } catch (err) {
    logger.error("POST /api/b2b/einladen", { error: String(err) });
    return NextResponse.json({ error: "Interner Serverfehler" }, { status: 500 });
  }
}
